// ─── Aptiv Bookkeeping CRM — South Africa Mock Data ────────────────────────────
// All monetary values stored as integer cents (ZAR)
// e.g. R10,000.00 = 1000000

export const mockMembers = [
  {
    id: 'm1', member_number: 'RC-2026-001',
    first_name: 'Thandiwe', last_name: 'Nkosi',
    sa_id_number: '8503150456080', sars_tax_number: '9012345678',
    date_of_birth: '1985-03-15', gender: 'Female', nationality: 'South African',
    phone: '27823341187', email: 'thandiwe.nkosi@email.com',
    province: 'Gauteng', physical_address: '14 Jorissen Street, Braamfontein, Johannesburg',
    fica_status: 'Verified', aml_risk_rating: 'Low', aml_pep_status: false,
    member_type: 'Individual', status: 'Active',
    cbda_member_class: 'Individual', cbda_admission_date: '2024-01-15',
    share_capital: 500000, savings_balance: 4822000, loan_balance: 1250000,
    fica_doc_id_verified: true, fica_doc_address_verified: true, fica_doc_income_verified: true,
    source_of_funds: 'Employment', source_of_funds_docs: true,
    bridge_synced: true, created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'm2', member_number: 'RC-2026-002',
    first_name: 'Sipho', last_name: 'Dlamini',
    sa_id_number: '7811045123083', sars_tax_number: null,
    date_of_birth: '1978-11-04', gender: 'Male', nationality: 'South African',
    phone: '27739082214', email: 'sipho.dlamini@email.com',
    province: 'KwaZulu-Natal', physical_address: '8 Anton Lembede Street, Durban',
    fica_status: 'Incomplete', aml_risk_rating: 'Medium', aml_pep_status: false,
    member_type: 'Individual', status: 'Active',
    cbda_member_class: 'Individual', cbda_admission_date: '2024-03-01',
    share_capital: 200000, savings_balance: 3194000, loan_balance: 0,
    fica_doc_id_verified: true, fica_doc_address_verified: false, fica_doc_income_verified: false,
    source_of_funds: 'Business', source_of_funds_docs: false,
    bridge_synced: false, created_at: '2024-03-01T09:30:00Z',
  },
  {
    id: 'm3', member_number: 'RC-2026-003',
    first_name: 'Lerato', last_name: 'Mokoena',
    sa_id_number: '9204220387087', sars_tax_number: '9023456781',
    date_of_birth: '1992-04-22', gender: 'Female', nationality: 'South African',
    phone: '27842279903', email: 'lerato.mokoena@email.com',
    province: 'Western Cape', physical_address: '22 Long Street, Cape Town',
    fica_status: 'Verified', aml_risk_rating: 'High', aml_pep_status: true,
    member_type: 'Individual', status: 'Active',
    cbda_member_class: 'Individual', cbda_admission_date: '2023-11-20',
    share_capital: 1000000, savings_balance: 1278000, loan_balance: 820000,
    fica_doc_id_verified: true, fica_doc_address_verified: true, fica_doc_income_verified: true,
    source_of_funds: 'Business', source_of_funds_docs: true,
    bridge_synced: true, created_at: '2023-11-20T11:00:00Z',
  },
  {
    id: 'm4', member_number: 'RC-2026-004',
    first_name: 'Johan', last_name: 'van der Merwe',
    sa_id_number: '6907315099085', sars_tax_number: null,
    date_of_birth: '1969-07-31', gender: 'Male', nationality: 'South African',
    phone: '27827714455', email: null,
    province: 'Free State', physical_address: 'Kellner Street, Bloemfontein',
    fica_status: 'None', aml_risk_rating: 'Low', aml_pep_status: false,
    member_type: 'Individual', status: 'Active',
    cbda_member_class: 'Youth', cbda_admission_date: '2025-01-10',
    share_capital: 100000, savings_balance: 9641000, loan_balance: 4500000,
    fica_doc_id_verified: true, fica_doc_address_verified: false, fica_doc_income_verified: false,
    source_of_funds: null, source_of_funds_docs: false,
    bridge_synced: false, created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'm5', member_number: 'RC-2026-005',
    first_name: 'Ubuntu', last_name: 'Farmers Co-operative Ltd',
    sa_id_number: null, sars_tax_number: '9034567892',
    date_of_birth: null, gender: null, nationality: 'South African',
    phone: '27865678901', email: 'ubuntu.farmers@coop.co.za',
    province: 'Mpumalanga', physical_address: 'Nelspruit CBD, Mpumalanga',
    fica_status: 'Verified', aml_risk_rating: 'Low', aml_pep_status: false,
    member_type: 'Co-operative', status: 'Active',
    cbda_reg_number: 'CBDA/CFI/2022/0456',
    cbda_member_class: 'Institutional', cbda_admission_date: '2022-06-01',
    share_capital: 5000000, savings_balance: 12000000, loan_balance: 8000000,
    fica_doc_id_verified: true, fica_doc_address_verified: true, fica_doc_income_verified: true,
    source_of_funds: 'Agricultural Income', source_of_funds_docs: true,
    bridge_synced: true, created_at: '2022-06-01T10:00:00Z',
  },
]

export const mockPaymentTransactions = [
  {
    id: 'p1', member_id: 'm1', member_name: 'Thandiwe Nkosi',
    gateway_reference: 'PGW-2026-0001A', payer_reference: '27823341187',
    amount_zar: 500000, transaction_type: 'Instant EFT',
    transaction_date: '2026-07-10T14:22:00Z', status: 'Completed',
    gateway_result_code: '0', gateway_result_desc: 'Payment processed successfully.',
    bookkeeping_synced: true, fica_flag: false, narrative: 'Monthly savings deposit',
  },
  {
    id: 'p2', member_id: 'm2', member_name: 'Sipho Dlamini',
    gateway_reference: 'PGW-2026-0002B', payer_reference: '27739082214',
    amount_zar: 2500000, transaction_type: 'Payment Request',
    transaction_date: '2026-07-09T09:15:00Z', status: 'Completed',
    gateway_result_code: '0', gateway_result_desc: 'Payment processed successfully.',
    bookkeeping_synced: false, fica_flag: true, narrative: 'Loan repayment',
  },
  {
    id: 'p3', member_id: 'm3', member_name: 'Lerato Mokoena',
    gateway_reference: 'PGW-2026-0003C', payer_reference: '27842279903',
    amount_zar: 1500000, transaction_type: 'Card Payment',
    transaction_date: '2026-07-08T11:45:00Z', status: 'Completed',
    gateway_result_code: '0', gateway_result_desc: 'Payment processed successfully.',
    bookkeeping_synced: true, fica_flag: true, narrative: 'Large deposit — FICA review triggered',
  },
  {
    id: 'p4', member_id: 'm5', member_name: 'Ubuntu Farmers Co-operative Ltd',
    gateway_reference: 'PGW-2026-0004D', payer_reference: 'ACC-4092881',
    amount_zar: 4500000, transaction_type: 'Payout',
    transaction_date: '2026-07-07T08:00:00Z', status: 'Completed',
    gateway_result_code: '0', gateway_result_desc: 'Payment processed successfully.',
    bookkeeping_synced: true, fica_flag: true, narrative: 'Member dividend payout',
  },
]

export const mockComplianceFlags = [
  {
    id: 'f1', member_id: 'm3', member_name: 'Lerato Mokoena',
    severity: 'HIGH', flag_type: 'PEP Detection',
    description: 'Member identified as Politically Exposed Person (PEP). Enhanced Due Diligence required under FIC Act s21.',
    regulatory_body: 'FICA', regulatory_ref: 'FICA s21 — Enhanced Due Diligence',
    str_required: true, str_filed: false,
    status: 'Open', detected_date: '2026-07-08',
  },
  {
    id: 'f2', member_id: 'm3', member_name: 'Lerato Mokoena',
    severity: 'HIGH', flag_type: 'Large cash deposit without verified FICA',
    description: 'Payment transaction of R15,000.00 exceeds the R10,000.00 FICA cash threshold. STR filing required within 3 working days.',
    regulatory_body: 'FICA', regulatory_ref: 'FIC Act s28(1)',
    str_required: true, str_filed: false,
    status: 'In Review', detected_date: '2026-07-08',
  },
  {
    id: 'f3', member_id: 'm2', member_name: 'Sipho Dlamini',
    severity: 'MEDIUM', flag_type: 'FICA documentation outstanding',
    description: 'Member FICA incomplete: proof of address and source of funds documentation outstanding. Required within 30 days.',
    regulatory_body: 'FICA', regulatory_ref: 'FICA s21(1)(b)',
    str_required: false, str_filed: false,
    status: 'Open', detected_date: '2026-07-01',
  },
  {
    id: 'f4', member_id: 'm4', member_name: 'Johan van der Merwe',
    severity: 'MEDIUM', flag_type: 'Missing SARS tax reference',
    description: 'SARS tax reference number not captured. Required for tax compliance reporting.',
    regulatory_body: 'SARS', regulatory_ref: 'Internal credit policy 4.2',
    str_required: false, str_filed: false,
    status: 'Open', detected_date: '2026-07-10',
  },
  {
    id: 'f5', member_id: 'm1', member_name: 'Thandiwe Nkosi',
    severity: 'LOW', flag_type: 'Annual FICA refresh due',
    description: 'Annual FICA refresh overdue by 15 days. SARB requires annual review for all members.',
    regulatory_body: 'SARB', regulatory_ref: 'SARB Directive 1/2022',
    str_required: false, str_filed: false,
    status: 'Open', detected_date: '2026-07-01',
  },
]

export const mockCbdaReport = {
  id: 'cr1', report_type: 'Quarterly Prudential',
  period: '2026-Q2', due_date: '2026-08-31', status: 'Pending',
  capital_adequacy_ratio: 14.2,
  liquidity_ratio: 18.5,
  loan_to_asset_ratio: 52.3,
  external_borrowing_ratio: 8.1,
  total_assets_zar: 415952172,
  total_deposits_zar: 341278000,
  total_loans_zar: 291430000,
  total_equity_zar: 71856972,
}

export const mockSettings = {
  org_name: 'SA Aptiv Bookkeeping CRM',
  currency: 'ZAR',
  financial_year_end: '28 February',
  sarb_cfi_licence: '',
  cbda_registration: '',
  vat_number: '',
  province: 'Gauteng',
  fica_cash_threshold: 1000000,
  dormancy_period_months: 12,
  gateway_provider: '',
  gateway_env: 'sandbox',
  bridge_enabled: false,
}

export const mockUsers = [
  { id: 'u1', email: 'admin@aptivcrm.co.za', first_name: 'Neal', last_name: 'Titus', role: 'Admin', status: 'Active' },
  { id: 'u2', email: 'compliance@aptivcrm.co.za', first_name: 'Jane', last_name: 'van Wyk', role: 'Compliance Officer', status: 'Active' },
  { id: 'u3', email: 'coo@aptivcrm.co.za', first_name: 'David', last_name: 'Mahlangu', role: 'COO', status: 'Active' },
]
